/**
 * Unified error codes for the entire NanoClaw application.
 */
export enum ErrorCode {
  DB_NOT_INITIALIZED = 'DB_NOT_INITIALIZED',
  DB_CONSTRAINT = 'DB_CONSTRAINT',
  CONTAINER_SPAWN_FAILED = 'CONTAINER_SPAWN_FAILED',
  CONTAINER_GATEWAY_FAILED = 'CONTAINER_GATEWAY_FAILED',
  CONTAINER_KILLED = 'CONTAINER_KILLED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  DELIVERY_NO_ADAPTER = 'DELIVERY_NO_ADAPTER',
  DELIVERY_MAX_RETRIES = 'DELIVERY_MAX_RETRIES',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  UNKNOWN_SENDER = 'UNKNOWN_SENDER',
  ROUTE_NO_AGENT = 'ROUTE_NO_AGENT',
  ROUTE_DROPPED = 'ROUTE_DROPPED',
  ATTACHMENT_UNSAFE = 'ATTACHMENT_UNSAFE',
  PATH_ESCAPE = 'PATH_ESCAPE',
  EGRESS_LOCKDOWN_FAILED = 'EGRESS_LOCKDOWN_FAILED',
  ONECLI_GATEWAY_FAILED = 'ONECLI_GATEWAY_FAILED',
  MODULE_NOT_INSTALLED = 'MODULE_NOT_INSTALLED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  AGENT_GROUP_NOT_FOUND = 'AGENT_GROUP_NOT_FOUND',
  MESSAGING_GROUP_NOT_FOUND = 'MESSAGING_GROUP_NOT_FOUND',
  CONTAINER_CONFIG_NOT_FOUND = 'CONTAINER_CONFIG_NOT_FOUND',
  UPGRADE_TRIPWIRE = 'UPGRADE_TRIPWIRE',
  CIRCUIT_BREAKER = 'CIRCUIT_BREAKER',
}

/**
 * Application error with structured context.
 */
export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly context?: Record<string, unknown>,
    public readonly recoverable = true,
  ) {
    super(message);
    this.name = 'AppError';
  }
}
